### ISSUE TITLE
When network is disconnected, videos do not continue to play from cache.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-video#103]
<b>How it works now:</b>
1. Add a video (webm or MP4) to a Presentation using the Video Widget. Confirm that it downloads and plays from the cache on the Display. You can do this by adding browserarguments=--remote-debugging-port=9876 to RiseDisplayNetworkII.ini, and then opening Chrome and navigating to http://localhost:9876 on the Display.
2. Disconnect the network from the Display while the video is playing. Notice that when the video loops to restart, it stays on the loading spinner animation. 

<b>How it should work:</b>
If you have images in your Presentation, they continue to work from cache when the network is disconnected. Videos should do the same.

This was tested on Windows 10, 7, and Ubuntu.

This is the Presentation used for testing.
https://apps.risevision.com/editor/workspace/155cba84-a665-4fc0-9b93-e18376ceafcd/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

**Comment by stulees** [comment]
This has been fixed and deployed by PR #105 , closing. FYI @robb-price
