### ISSUE TITLE
Video Content not showing when network does not have 100% reliability/stability

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-video#107]
**How to recreate**
1. Add a supported video (.webm) in the Video Widget and publish the Presentation
2. Using a throttle simulator/web debugging proxy (ie <a href="https://www.charlesproxy.com/documentation/proxying/throttling/">Charles</a>) set the:
-- bandwidth to 2048kbps
-- reliability 95%
-- stability 95%
-- leave other settings as is

**What happens**
When you play the video without the throttling simulator, the video plays from cache (http://localhost:9494/?url=)

When you start the throttling simulator, the video turns to a black screen. 

Along with the black screen a user has also reported seeing the Chrome frown face:
<img width="947" alt="screen shot 2016-03-22 at 11 39 42 am" src="https://cloud.githubusercontent.com/assets/5868781/13958424/672a6696-f026-11e5-932e-b4a8ca82b6f1.png">

When you run the Display ID in BQ
`
SELECT * FROM [Widget_Events.VideoErrorsDaily] where display_id = 'DISPLAY_ID_TO_BE_SUPPLIED' order by ts 
`

It will show in **file_url** the video is playing from cache and the **error** message **player error - video - Error loading media: File could not be played**

**What should happen**
1. On a network with less than 100% reliability/stability, the video should continue to play from cache.
2. When the error occurs, the Widget should state what the error message is similar to the error message being shown in BQ.

**Notes**
Tested on Win 7 x64
In the throttle test the screenshot below also shows further info:
<img width="947" alt="screen shot 2016-03-22 at 11 39 42 am" src="https://cloud.githubusercontent.com/assets/5868781/13936681/abbf573a-ef95-11e5-90ee-96711b8cd720.png">
When the error occurs, the user can recover by restarting Rise Player

**Comment by hcs0** [comment]
Bug report has been updated to include further info from BQ and a screenshot showing the Chrome frown face and black screen

**Comment by alanclayton** [comment]
@hcs0 @rodrigopavezi is this fixed now?

**Comment by hcs0** [comment]
@alanclayton @rodrigopavezi Yes. I haven't seen the Chrome error/black screen on the Display that has this. On another Display that is on the same network that doesn't have the modified cache, the black screen/Chrome error has come up.

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/hcs@risevision.com/conversations/4357575829
