### ISSUE TITLE
~10 sec delay playing video from Rise Cache w/ no network

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-video#124]
Using ver 1.1.0, if you remove network from the media player, and the video it is playing is saved in Rise Cache, it will take ~10 sec before the video plays. During that you see a jwplayer loading animation. 

Since we have the video stored locally, we shouldn't be seeing any delays playing the video.

**Comment by stulees** [comment]
@alanclayton At what point was network removed and when was it restored?

**Comment by alanclayton** [comment]
@stulees network was removed after the video played one full cycle to ensure it was stored in Rise Cache. Left network unplugged for another two full cycles.

**Comment by alanclayton** [comment]
Will be addressed with new Rise Cache.
