### ISSUE TITLE
Videos cannot be paused/resumed on an interactive touchscreen Display

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-video#128]
<b>How it works now:</b>
1.Create a Presentation with a video, and ensure that the mouse pointer is NOT hidden. Play this Presentation on a Display.
2. Notice that when you interact with the video to pause and resume on an interactive screen, that the video pauses for a millisecond, then continues playing. You cannot successfully pause the video, but you can use the progress slider to change the video position.

Presentation to test with: https://apps.risevision.com/editor/workspace/ad03f1f5-cf40-49eb-9798-734c7607cb37/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

<b>How it should work:</b>
When you interact with the video, it should pause when touched, and unpause when touched again.

**Comment by hcs0** [comment]
@rodrigopavezi To confirm, the **user will need to double tap the screen** since it's the way jwplayer implementing the touch event differently depending on the browser and device.  Will close since it's not a widget issue.
