### ISSUE TITLE
No video in risevision since yesterday

### ISSUE THREAD

**Issue by movitch** [Rise-Vision/widget-video#133]
Hi,
sorry by advance i don't know if it's the good way to report a problem. 

I opened an incident on risevision community. Since yesterday my videos no longer work on risevision [https://community.risevision.com/rise_vision_inc/topics/white-screen-cpwgvvxiojv51]. Does this could come from the latest version of the widget ? Thank you in advance.

**Comment by alanclayton** [comment]
@movitch We're going to close this issue. Let us know in the Community if you're still having problems. 

Thanks!
