### ISSUE TITLE
Incorrect error message on video widget when http:// is missing from link

### ISSUE THREAD

**Issue by raydurkin** [Rise-Vision/widget-video#136]
**What is happening:**
When a link to a custom URL is put in the Video Widget and that link does not have an http:// header, you will get the following error when you preview: "There was a problem playing that video. It could be that we don't support that format or it is not encoded correctly."     And you get the following error message on the display: "There was a problem retrieving the file from Rise Cache"

**How to recreate:**
Put a link to a custom URL video in the Video widget and leave off the http:// at the beginning of the URL.  Save and publish.  Preview the presentation and assign it to a display to see the two messages.

**What should happen**
When a link to a customer URL is put in the Video Widget and that link does not have an http:// header, a more meaningful error message should show up to be able to identify the issue quickly - or the widget should just add the http:// header - I don't know the best solution
Also - the error message on the display and in preview should be the same

**Comment by donnapep** [comment]
@raydurkin Can you please provide a link to a Presentation showing the problem? Thx.

**Comment by donnapep** [comment]
Example Presentation - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=968daa77-53e4-4fef-b5c2-8a8fd97fb3ee?cid=bb776dc3-6e7b-4993-98dd-511f6aa1dbd7

**Comment by stulees** [comment]
@raydurkin This was fixed in PR #137 , closing, thanks.
