### ISSUE TITLE
Sometimes after all videos are done downloading, the "Please wait while your video is downloading" message still appears and the videos do not start.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-video#180]
<b>How it works now:</b>
1. Play <a href="https://apps.risevision.com/editor/workspace/bde2ba10-d4df-4bca-b30a-45010428343a/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a> on a Display. Notice that while the videos are all downloading, you see the message "Please wait while your video is downloading".
2. Once the videos are done downloading, notice that the message does not go away, even after 10/15 minutes, and no videos start playing.
3. If you save the Schedule or Presentation after that, all videos start playing.

No errors are obvious in the logs for the Displays running this Presentation, outside of one of the videos reports a 404.

For further clarification: https://goo.gl/jHq2DV

Some users have reported that after a couple of days, this occurs again, and they need to save the Presentation to play the videos again.

<b>How it should work:</b>
Once the videos are done downloading, they should start playing.

**Comment by stulees** [comment]
@robb-price This was fixed with PR #181 , closing.
