### ISSUE TITLE
External Video causes the Presentation to sit on "File is Downloading" screen

### ISSUE THREAD

**Issue by stulees** [Rise-Vision/widget-video#184]
<b>How it works now:</b>
1. Play <a href="https://apps.risevision.com/editor/workspace/cde05210-5cfe-4280-91bd-7a8356981113/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a> on a Display. Notice that when it reaches the Jul.webm video which is hosted externally, it sits on the File is Downloading window, and never recovers.
2. If you restart the Player, it plays just fine.

Hosting the video at Rise Storage does not have this issue.

<b>How it should work</b>
Regardless if the Video is external, it should download and play.

**Comment by stulees** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 78 - External Video sits on File is Downloading screen](https://trello.com/c/RlwfTrzp/2949-1-issue-78-external-video-sits-on-file-is-downloading-screen)

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 78 - External Video sits on File is Downloading screen](https://trello.com/c/RlwfTrzp/2949-1-issue-78-external-video-sits-on-file-is-downloading-screen)

**Comment by robb-price** [comment]
Verified and Closed.
