### ISSUE TITLE
Black screen after some time

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/widget-video#203]
**How it works now:**
We are seeing video widgets go black after some time. We can fix this be re-saving the schedule or presentation, but will eventually go black in about 5-20 minutes

**How it should work:**
Video widget is not black

**Information:**
Displays where it has been replicated:
https://connect.risevision.com/Host#Access/*Rise%20Display%20Creative//e3ae0bd6-185e-4611-9503-4d73a5b5e6df

CUHAR8BET4KB [Screenconnect](https://connect.risevision.com/Host#Access/All%20Machines/Tyler%20Wight/95853311-283a-42b2-99a2-feb62ca575bd)

QUA7BMZUGCBX

**Comment by sheadarlison** [comment]
@tylermwight This is fixed, I'm closing the issue, please reopen it if any user reports otherwise. Thanks
