### ISSUE TITLE
Presentation is sitting on File is Downloading when Videos are in Presentation

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-video#210]
### What is the expected behavior?
The Display should download and play all videos in the Presentation.

### What is the actual behavior?
The Presentation gets to a specific point in the Presentation and then sits on the "File is Downloading" message. There is nothing obvious in the Network Tab from what I can see that would indicate the error:
![2018-04-24_13-58-19](https://user-images.githubusercontent.com/6862256/39205064-a936898e-47c7-11e8-9d75-2be79a31538a.png)

### What steps can be taken to replicate the problem?
I have been able to replicate this by playing a Presentation that a user reported as having the issue.

The Presentation, and SC link to my Display that is hving the issue will be included in the Trello card.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 210: Presentation sitting on "Files are Downloading"](https://trello.com/c/gQ6PzEtl/7880-issue-210-presentation-sitting-on-files-are-downloading)

**Comment by stulees** [comment]
The fix has been deployed with the use for RLS for Folder.
