### ISSUE TITLE
Videos do not autoplay in preview despite being set to in the settings, even if they are set to no volume.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-video#213]
### What is the expected behavior?
When the Widget is set to Autoplay, and muted, despite <a href="https://developers.google.com/web/updates/2017/09/autoplay-policy-changes">this change</a> from Google Chrome's Developers to Google Chrome, the video should play.

### What is the actual behavior?
If you preview in Google Chrome, it will not autoplay. If you preview in Firefox, it will autoplay.

### What steps can be taken to replicate the problem?
Add a video to a Presentation, set it to mute if desired, and notice that the video does not autoplay in Chrome.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Issue 213: Videos do not autoplay](https://trello.com/c/SHrvkmoY/7942-3-issue-213-videos-do-not-autoplay)

**Comment by jungeunyoon** [comment]
**Problem**
If you @santiagonoguez view Video Widget in Google Chrome, it will not autoplay.

**Solution** 
- Video Widget should default to 0 for volume settings
- Video with volume at 0 should autoplay in both preview and on display, muted on all.
- Video with volume not at 0 should autoplay in both preview and on display, muted on preview, unmuted on Display

**How to validate** 
Do one of the following: 
1. Add a new Video Widget
2. Go into settings in presentation(s) and re-save video widget.

**Comment by jungeunyoon** [comment]
@robb-price Actually, as per Content Team's new Process for Releasing Changes we're going to leave this issue open for 24 hours. Thanks!

**Comment by robb-price** [comment]
@jungeunyoon Got it.
