### ISSUE TITLE
HTML5 Video Widget does not scale.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-video#22]
Steps to reproduce:
1. Add HTML5 Video Widget to placeholder
2. Drag placeholder to desired resolution

Result:
Video does not scale in placeholder, instead the video retains it's default resolution and the remainder of the placeholder is filled with a background.

How it should work:
This should work just like the Video Item. If a video item is added to a placeholder with a custom resolution it should scale to fit the placeholder.

Link to Presentation:
http://rva.risevision.com/#PRESENTATION_MANAGE/id=1a92a47f-1dbe-4597-8446-2d9dcbb66252/company=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
ALL

Player:
Chrome App Player

Chrome Ver:
Google Chrome 40.0.2214.115 (64-bit)

**Comment by btfrise** [comment]
@stulees I know you are currently working on the video widget. Can this be resolved in conjunction with your current work?

**Comment by stulees** [comment]
@btfrise @alanclayton To clarify, the Video Widget is responsive and does scale *down*, but I had intentionally made it not scale bigger than its actual size as I wasn't sure if this was really desired or not. Also, by not scaling bigger, it provided a way to make use of a background (color or image). 

If I make this fix, it will basically make the Background irrelevant. Shall I remove the Background setting while making this fix then?

**Comment by alanclayton** [comment]
@stulees not looking to add complexity, but does it make sense to let the User decide if they want to scale up?

**Comment by stulees** [comment]
@alanclayton It does make sense but in thinking about this further and knowing that Video Folder Widget is going to definitely scale up (I need to use a third party plugin), I'm thinking we should be consistent and scale up in this widget too. If I see if there is still potential for the Background Setting to be used then I'll keep it in, otherwise I'm going to remove it. Sound okay? @btfrise FYI

**Comment by ByronDarlison** [comment]
@stulees can we give the user the option to scale regardless? 

Scale To Fit [ ]

And keep the background component so that they can take advantage of both?

Thanks!

**Comment by stulees** [comment]
@ByronDarlison Sure lets do the option to scale. It's a little different doing this for video as opposed for an image but I don't think it should be a problem. Thanks @alanclayton @btfrise FYI

**Comment by alanclayton** [comment]
@stulees @ByronDarlison Agreed. Is the plan then to make this change your current wip?

**Comment by stulees** [comment]
@alanclayton I've shifted cards to make this a priority, and then will follow it up with the polling non-storage URLs http://goo.gl/qEyP3C . Good with you?

**Comment by alanclayton** [comment]
I defer to @btfrise

**Comment by btfrise** [comment]
There is an open complaint in the community regarding the HTML5 Video Widget not scaling up. With the pull of the video item slated for the 16th, I think we should get this taken care of first.

@stulees @alanclayton

**Comment by stulees** [comment]
@btfrise No problem, thanks

**Comment by stulees** [comment]
@btfrise @alanclayton The issue has been fixed, thanks.
