### ISSUE TITLE
Playing a folder of videos only plays the first video then a black screen

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-video#243]
### What is the expected behavior?
All videos in the folder download and play.

### What is the actual behavior?
Videos download, but only one plays, then the screen goes black.

### What steps can be taken to replicate the problem?
1. Create a folder of videos
2. Use the Video Widget in a Presentation to watch that folder.
3. Ensure that none of the files have been on the Display before by clearing the cache.
4. Run Player, and it will show 1 video, and then sit on a black screen.

For further clarification: https://goo.gl/xyFkx9

(excuse any audio cuts in the video, I edited it to shorten it.)

**Comment by sheadarlison** [comment]
@robb-price can you please attach links to the presentation and display affected to this card https://trello.com/c/Jftba7gn/5834-widget-video-issue-243

Thanks

**Comment by robb-price** [comment]
@sheadarlison Done.

**Comment by stulees** [comment]
@robb-price What issue were you investigating to want to delete all cached files manually from _local_storage/cache_? Are you able to reproduce this with any folder of videos without deleting all cached files from _local_storage/cache_? If you delete those files manually, it is most likely causing a sync issue with local storage database and Messaging Service, resulting in a problem with the Widget.

**Comment by robb-price** [comment]
@stulees Originally I was not able to recreate the issue with files that had already been downloaded to \rvplayer\modules\local-storage\cache, but I was able to, when the cache folder was cleared, so there was nothing downloaded, and the files are newly downloaded to the machine for the first time.

Wouldn't that be the situation when users are playing files for the first time on a Display?

**Comment by robb-price** [comment]
@sheadarlison @stulees Not sure if this little tidbit helps, but if you restart the Display or Player while it is on the black screen, everything appears to work as expected. All videos start, no black screen, etc.

**Comment by sheadarlison** [comment]
@robb-price did a user report the issue and were you able to reproduce by doing a fresh install and scheduling a folder of videos? 

After you restart the display or player does the black screen come back?

Thanks

**Comment by robb-price** [comment]
@sheadarlison A user reported the issue. After you restart, the videos work, however this user is often changing the folder the Display, and new Displays they are bringing on point to. So it continues to happen every time they change folders.

**Comment by sheadarlison** [comment]
@robb-price is it possible to recreate the issue without manually deleting the files, can you do it by following the same steps as the user?

**Comment by robb-price** [comment]
@sheadarlison I haven't been able to, but @tylermwight had this issue the first time he tried playing their Presentation, and the user apparently has it pretty constantly. I was only able to recreate it when I cleared the cache.

**Comment by sheadarlison** [comment]
@robb-price I reproduced and we're looking into it. Thanks

**Comment by robb-price** [comment]
@sheadarlison Awesome. Thanks!

**Comment by robb-price** [comment]
@sheadarlison @stulees User reports that the issue has not happened again, and all has been running fine since yesterday, so he is good to close this until he can reliably recreate it. Closing this issue.
