### ISSUE TITLE
Video Widget intermittently playing video

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/widget-video#246]
- Operating System Version: 64-bit Ubuntu 18.04.1 LTS (But it also happens on Ubuntu 16.04)
- Player Version: RisePlayerElectron 2018.09.10.12.32 Licensed
- Viewer Version: 2-01-201808201721

Media Player is a Compute Stick

##### What is the expected behavior?
Video Widget pointed to a folder of videos should play through them without any issues.

##### What is the actual behavior?
Video Widget pointed to a folder of videos goes to a black screen instead of loading the video.

##### What steps can be taken to replicate the problem? 
1. Create a Presentation with a single placeholder and add a Video Widget to it.
2. Point the Video Widget to a folder of videos.
3. Assign the Presentation to a test Display.
4. Start Rise Player on the test Display. If it loads the videos the first time, kill Rise Player and start it again.

**Comment by sheadarlison** [comment]
Hardware is under powered, closing the issue
