### ISSUE TITLE
Presentations contain old video widgets which aren't using RLS

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/widget-video#250]
We still have presentations that contain old video widgets.
These widgets are not using RLS, and so the displays cause bandwidth problems and result in throttled files and blank displays.

In addition, the widgets aren't logging the display id into BigQuery which makes troubleshooting difficult.

Here's a sample presentation containing an old widget. This comes from today's highest bandwidth offender.
https://apps.risevision.com/editor/workspace/cf220433-156a-4234-9361-ac74405b224a//htmleditor?cid=54539e74-0ff9-4ea6-b83f-33c61bbd4d65

**Comment by stulees** [comment]
@tejohnso I think this would be better served as a _Delivery Request_ on our board to address as opposed to an issue against the Video widget. Your description does not imply there is an issue with the latest Widget itself, so there will be nothing to change in code to fix this problem.

**Comment by stulees** [comment]
This was fixed from our batch re-write of video widget URLs ( `1.0.0` -> `1.1.0`) in presentations.
