### ISSUE TITLE
Offline Play not working after reboot

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/widget-video#255]
### What is the expected behavior? 

Once losing network connectivity and rebooting, offline play should display the last presentation without issue.

### What is the actual behavior? 

Once network connectivity is lost and the device is rebooted, the device is stuck on "downloading video".

### What steps can be taken to replicate the problem?
1. Schedule a presentation with supported offline content.
2. Wait for the content to download on the presentation.
3. Pull the ethernet cable out of the device.
4. Reboot.

**Comment by tejohnso** [comment]
@robb-price closing this as discussed https://trello.com/c/C7e8CSvO/4895-3-widget-video-issue-255-2
