### ISSUE TITLE
Video failing to play with media corruption error

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/widget-video#256]
Operating System | 64-bit Microsoft Windows 10 Pro
Player Version | RisePlayerElectron 2018.11.26.15.49 Licensed
Viewer Version | 2-01-201811191457

**Expected Behavior:**
A video should play on a Display indefinitely without running into any errors.

**Actual Behavior:**
Playing a video on a Display eventually results in this error: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

**Steps to reproduce:**
**Note: I could not reproduce this issue on my own hardware**

1. Create a Presentation with a single video widget pointed to an mp4 or webm file in storage.
2. Schedule that Presentation to a Display and wait.

**Comment by stulees** [comment]
Issue fixed with #257
