### ISSUE TITLE
When added as an embedded presentation, HTML5 Video Widget loops endlessly.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-video#28]
Steps to reproduce:
1. Create presentation with only HTML5 video widget. Save presentation.
2. Create another presentation with one large placeholder, add multiple embedded presentations. Add the presentation containing the HTML4 Video Widget.
3. Set HTML5 Video Widget presentation to Play Until Done.

Result:
The presentation playlist stops at the HTML5 Video Widget presentation and the video endlessly loops.

How it should work:
The placeholder should move on to the next item in the presentation playlist.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=fcbae24f-ec23-4622-9981-7a50c771726c

OS:
OS X 10.10.2 / ChromeOS / Linux Ubuntu 14.04 (Chrome App Player)

Chrome Ver:
41.0.2272.89

**Comment by stulees** [comment]
@btfrise The HTML5 Video Widget always makes the `"rsevent_done"` call to the Viewer at the end of a video duration. If it is endlessly looping then there is an issue with the Viewer not receiving the `done` call, perhaps due to it being within an embedded presentation. There is never an issue with continuous looping when the Widget is **not** used within an embedded presentation, correct?

**Comment by btfrise** [comment]
@stulees That is correct.

**Comment by stulees** [comment]
@btfrise Okay. @alex-deaconu Any thoughts about this? Do you see a possible bug/issue with Viewer in this situation?

**Comment by alex-deaconu** [comment]
@btfrise @stulees from what I can tell the Widget is sending the done command correctly. This may be an issue with the Viewer, or the configuration of the embedded presentations. Thanks.

**Comment by stulees** [comment]
@alex-deaconu Thanks. @btfrise This doesn't appear to be an issue specifically with HTML5 Video Widget. Aside from re-checking the configuration of embedded presentations as Alex suggested, I would try recreating this scenario with a different Widget that requires calling the done command and see if it results in the same problem. Widgets like Text and Spreadsheet widget, when set to autoscroll, call done when the autoscroll is complete. Image Folder Widget is another one that calls done command when it finishes the cycle of images. 

If the same problem is happening when trying a different Widget, then this issue should be logged against the Viewer. Thanks

**Comment by btfrise** [comment]
@stulees Thanks for the review. I'll do some testing and close this issue if needed.

**Comment by btfrise** [comment]
@stulees I'm getting the same issue with the calendar widget when set to scroll. I'm closing this and relogging against the viewer repo.
