### ISSUE TITLE
4:3 Videos cannot be centered. 

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-video#31]
Steps to reproduce:
1. Add a 4:3 video to a 16:9 HTML5 Video Widget placeholder.
2. Save and preview presentation.

Result:
The 4:3 video aligns to the left of the widget.

How it should work:
4:3 videos should be centered in the placeholder.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=e36496a4-63be-4365-8aff-ebc6dd68bc3c

OS:
ChromeOS, Windows, Linux

Chrome Ver:
41.0.2272.89 (CAP)

**Comment by alanclayton** [comment]
@btfrise is this issue still relevant?

**Comment by btfrise** [comment]
This is resolved in the new widget. I am closing this issue.

FYI @alanclayton
