### ISSUE TITLE
Non-Storage Videos are Stuttering

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/widget-video#32]
Steps to reproduce:
1. Add multiple HTML5 Video Widgets with .webm videos to a placeholder from a location other than Rise Storage (I used Rise Vision Amazon S3)
2. Play presentation on a display

Result:
Some of the videos start stuttering, within a couple of minutes of the presentation starting, and persisted.  This happened on 3 of my displays.
Note that when I switched the gadget back to the same videos from Rise Storage, the stuttering stopped.

How it should work:
Video playback should be smooth.

Link to Presentation:
http://rvauser.appspot.com/#PRESENTATION_MANAGE/id=85b356fc-6d50-42d5-aca1-20d024ba07ea/company=cd7cb86b-8134-4c41-996c-d1ca82e5a1a9

OS:
Windows 

Chrome Ver:
Chrome 41.0.2272.101 (CAP)

**Comment by AlexKolenoff** [comment]
Update:

It appears that the non-Storage videos are not being cached which is probably the reason for the stuttering.

I checked cache here and it shows no files after playing the presentation for awhile: http://screencast.com/t/Vm1IlvYppnLz

**Comment by alanclayton** [comment]
@AlexKolenoff is this issue still relevant?

**Comment by AlexKolenoff** [comment]
@alanclayton No, I don't think so.
