### ISSUE TITLE
Videos stop playing after a while, leaving a black screen.

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-video#33]
Steps to reproduce:
- schedule presentation with multiple videos in a placeholder (untested if it occurs with just one video)
- let it run for some period of time (15 to 30 minutes) usually

Result:
- placeholder/video shows only a black screen (CPU usage seems to drop down to almost nothing)
- some time later (seems to be around 15 minutes or so) the videos will start up again.

How it should work:
- videos should play the entire time

Link to Presentation:
http://1-08-001.rvauser2.appspot.com/#/PRESENTATION_MANAGE/id=ef1914fe-1bb8-4112-95dc-e7672d79baeb?cid=e514fd51-fadd-4e19-94af-f92549772c7f    (my company, where the log came from)
and
http://1-08-001.rvauser2.appspot.com/#/PRESENTATION_MANAGE/id=153136b9-8dd3-41d1-84ec-918cc1748f16?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55    (uptime company)

OS:
- observed on Linux and ChromeOS as described
- windows seems to take longer, shows a blank/white screen

Chrome Ver:
40.0.2214.115 and 41.0.2272.89

Copy/Pasted log from the dev console can be downloaded here:
http://goo.gl/cgZwfT
The very bottom is during one of the black screen incidents.  Above/before that is normal operation

**Comment by alanclayton** [comment]
@mfisher11 is this issue still relevant?

**Comment by mfisher11** [comment]
This issue is resolved.  Closing.
