### ISSUE TITLE
Right clicking in video opens context menu that can redirect out of presentation

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-video#36]
* This applies to the testing version of the widget *

Steps to reproduce:
1. Assign a presentation containing the video widget to a display.
2. Right click on the video.

Result:
A context menu listing "About JWPlayer..." appears.  Clicking on that will open a new website, replacing the presentation.

How it should work:
No menu should appear when right clicking on the video.

Link to Presentation:
http://rva-test.appspot.com/#/PRESENTATION_MANAGE/id=d1139a47-3cea-4432-a78c-d966781ebd64?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

OS:
Ubuntu 14.04

Chrome Ver:
42.0.2311.152-1

**Comment by stulees** [comment]
@mfisher11 FYI closing this as its been fixed and deployed.
