### ISSUE TITLE
Looping video is not smooth

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/widget-video#40]
Steps to Reproduce
1. Add one or more videos to a placeholder (the shorter the video the more noticeable this is)
2. Assign to display/player

Result:
After the video ends, there is a flash of black (and sometimes also a small white loading circle) before the video starts playing again.

How it should work:
The video should start playing again with no noticeable delay in between the end of the last video and the beginning of the next video

Link to Presentation:

http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=c854bd6f-f73b-44ea-9b12-57e15b31dd43?cid=cd7cb86b-8134-4c41-996c-d1ca82e5a1a9

OS:
Windows 7

Chrome Ver:
44.0.2403.130 (CAP)

**Comment by stulees** [comment]
Seamless looping video is not achievable with the Widget in a presentation and an alternative solution should be taken by using an HTML file in a schedule. Closing @alanclayton FYI
