### ISSUE TITLE
When many videos are in a playlist, Player crashes due to low memory.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-video#49]
Steps to reproduce:
1. Create a presentation with a single placeholder.
2. Within that placeholder add Video Widgets referencing many different videos.

Result:
Memory usage on player will spike, resulting in a low on memory error message and player crash.

How it should work:
The Video widget should destroy it's iframe after each video and memory usage should reset.

Link to Presentation:
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=0293df1f-046d-40c7-bf26-e7fecc4109c4?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957

OS:
Ubuntu 14.04, Windows 7

Chrome Ver:
44.x, 46.x

Player Ver:
Rise Windows Player, Rise Linux Player, Rise Player Chrome Application.

Notes:
We re-encoded all videos in this presentation until the sum was under 600MB, and a crash was still reproduced. This was tested on a Windows 7 system with 4GB of ram, and an Ubuntu 14.04 system with 2GB of ram.

**Comment by stulees** [comment]
@btfrise Is there any reason why Video Folder Widget is not used in this situation of so many videos? Also, under *How it should work*, the Widget does internally destroy its <iframe> that contains the player/video on video completion and notifies done. Have you seen otherwise? Thanks

**Comment by alanclayton** [comment]
@stulees  User is looking for a specific order to play them in. As for memory usage, something doesn't sound right as I saw this presentation running and it went from 2 gb to 3.9 gb after running for ~10 minutes

**Comment by stulees** [comment]
@alanclayton Couple things to be aware of. User **can** achieve a specific order with Video Folder if they name their files in ascending alphabetic order as that is the default on how the playlist gets put together in the Widget. 

The other thing is that JS doesn't have explicit memory management, it's the browser which decides when to clean it up. So JS garbage collection is run when the browser decides to run it, which means you can't expect immediate memory to be released when a Video Widget completes playing (the `<iframe>` is destroyed). If there's , then this c

We'll investigate this issue further when we reach the card in Trello, but there should be some awareness going into it that there may be a limitation we can't work around regarding memory and a long playlist of Video Widgets with very large sized videos.

**Comment by alanclayton** [comment]
@stulees Understood on the ordering, but not always convenient if that means you have to change the name of all your other files to accommodate a new one! Let's see what you find once you look into this. Thanks

**Comment by alanclayton** [comment]
Issue is resolved.
