### ISSUE TITLE
Videos do not start over when replayed in schedule.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-video#74]
Reproduction steps
1. Create a schedule with multiple items, including at least 1 video.
2. Preview the schedule, or assign it to a display.

Expected results
1. As the schedule cycles through, each video should start over

Actual results
1. As the schedule cycles through, each video starts increasingly further into the video.

OS
OSX / Windows 7 64bit

Browser
Chrome 46.*

Schedule replication
http://preview.risevision.com/Viewer.html?type=schedule&id=553347c0-b817-4f4f-9efa-91a104f078d3

**Comment by btfrise** [comment]
FYI @alanclayton

**Comment by btfrise** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/btf@risevision.com/conversations/1513187828

**Comment by stulees** [comment]
@btfrise This is a behaviour of the Widget that has always existed and has been briefly discussed before in our Content team. It should not be considered a bug as there are use cases where the preference is how it currently works, the video does not start over again and continues from where it left off. 

@alanclayton @mmeiers We mentioned before the possibility of introducing a new setting that would allow for a user to choose whether they want their video(s) to continue where left off or completely start over. It looks like we might want to consider this feature sooner than later. @btfrise FYI

**Comment by btfrise** [comment]
Thanks for the clarification @stulees 

Compass Group has reported this issue.

**Comment by mmeiers** [comment]
@btfrise @stulees Ya its been like that for a while. I think the same thing happens if you have a playlist of images in a placeholder (presentations continuously play in the background). Which was why i was under the impression this was change that has to happen outside of the widget as well.

**Comment by alanclayton** [comment]
@btfrise Given this isn't an issue this should be closed and an idea should be posted in the Community to see what the response to it is. You agree?

@stulees @mmeiers

**Comment by btfrise** [comment]
@alanclayton agreed.

**Comment by btfrise** [comment]
@alanclayton @mmeiers @stulees Michelle @ Compass Group just brought up a great point. These videos are exactly 10 seconds long and the starting point is still varying. Can someone confirm for me why that is?

**Comment by mmeiers** [comment]
@btfrise Not sure without seeing their videos but Ive seen stuff be off because of fractions of a second. RVA doesnt tell you tenths of a second I would download the videos to verify that they are all exactly the same.

**Comment by alanclayton** [comment]
@btfrise Can you give us the Presentation?

**Comment by alanclayton** [comment]
@btfrise I suspect PUD is not enabled on the Video, but we can check for you if you can provide a link to the Presentation. Thanks

**Comment by btfrise** [comment]
@mmeiers Looks like it's not exactly 10 seconds in length.

**Comment by btfrise** [comment]
@alanclayton http://rva.risevision.com/?parentId=e113f8d6-de1c-4c26-b160-4ef1c4589957#/SCHEDULE_MANAGE/id=553347c0-b817-4f4f-9efa-91a104f078d3?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957

**Comment by alanclayton** [comment]
Issue is resolved.
