### ISSUE TITLE
Video Playlist Breaking With Schedule

### ISSUE THREAD

**Issue by ashleighalmeida** [Rise-Vision/widget-video#76]
What is happening:

From the Schedule, both presentations are configured with a duration of 10 seconds. If you Preview the Schedule you'll see Presentation 1:Video 1 play. After 10 seconds Presentation 2 will appear, but you can still hear the audio from Presentation 1:Video 1 AND you hear the audio for Presentation 1:Video 2.

What should happen:

Second scheduled presentation should appear at it's designated time. Instead, it is interrupting the first presentation at random intervals with audio bleeding.

Schedule replicating the issue: http://preview.risevision.com/Viewer.html?type=schedule&id=82fc96e9-7924-4625-8e2b-1c38d8146f16

Main Presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=4a54f45b-0be3-4d91-84e2-7571f584ca6e?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

Second Presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=4b6e3ce1-9d3f-4ce4-8b77-e51ac16bc877?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

**Comment by ashleighalmeida** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/apa@risevision.com/conversations/1476266404

**Comment by donnapep** [comment]
Fixed by PR #77.
