### ISSUE TITLE
Configured as Video Folder, a folder with only .mov files types displays incorrect error message.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-video#87]
Steps to reproduce:
1. Upload a .mov file to a storage folder
2. Add video widget to placeholder, configure as folder
3. Reference the folder that contains the .mov file
4. Assign to a schedule & display

Result:
The video widget displays "Please wait while your video is downloaded".

How it should work:
The video widget should display "Video format is not supported".

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=37766c98-cb39-41eb-a3f3-cfad51b83b22

OS:
OS X
Ubuntu 14.04 x32
Windows 7 x32

Chrome Ver:
47.*

**Comment by stulees** [comment]
@btfrise This has been fixed by PR #88 which has been deployed.
