### ISSUE TITLE
Incorrect error message displayed when disk is full.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-video#93]
**How to recreate**
1. Create a presentation with multiple videos (multiple single videos or folder)
2. Create a schedule, and add a Display ID that is attached to a Windows machine with less than 1GB of storage.

**What happens**
The video widget displays "There was a problem playing that video. It could be that we don't support that format or it is not encoded correctly."

**What should actually happen**
The Video Widget should reference that the video could not be downloaded and displayed due to a lack of storage space.

Windows 7 32bit
Rise Player Chrome App 
Rise Windows Player
Chrome 47.*

Schedule used for testing http://bit.ly/23eTeXH

**Comment by stulees** [comment]
@btfrise This was fixed by PR #99 , closing.
